# Generated by Django 5.0.2 on 2026-01-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_created_on_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='schemas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
