# Generated by Django 5.0.2 on 2026-02-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_schemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_on',
        ),
    ]
