# Generated by Django 5.0.2 on 2026-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_client_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='schemas',
        ),
        migrations.AddField(
            model_name='client',
            name='schema_file',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
