# Generated by Django 5.0.2 on 2026-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_options_alter_lead_extra_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields like company, industry, source, expected_close_date'),
        ),
    ]
