# Generated by Django 5.0.2 on 2026-01-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_lead_extra_data_lead_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Other custom fields like industry, source, budget, etc.'),
        ),
    ]
