# Generated by Django 5.0.2 on 2026-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_company_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='List of notes with text, user, and timestamp'),
        ),
    ]
