# Generated by Django 5.0.2 on 2026-01-30 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_notes_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('Finance', 'Finance & Banking'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Retail', 'Retail'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Cold Call', 'Cold Call'), ('Event', 'Event'), ('Email Campaign', 'Email Campaign'), ('Other', 'Other')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Other custom fields like budget, expected_close_date, decision_maker, etc.'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['industry'], name='crm_lead_industr_dce405_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source_0cf4cf_idx'),
        ),
    ]
