# Generated by Django 5.0.2 on 2026-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_industry_source_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_created_d9bbc3_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='new', max_length=30),
        ),
    ]
