# Generated by Django 5.0.2 on 2026-02-03 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_lead_crm_lead_created_d9bbc3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('use_same_legal_name', models.BooleanField(default=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('trading', 'Trading'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('construction', 'Construction'), ('food_hospitality', 'Food & Hospitality'), ('other', 'Other')], max_length=50, null=True)),
                ('trn', models.CharField(blank=True, help_text='15-digit TRN', max_length=15, null=True)),
                ('vat_treatment', models.CharField(blank=True, choices=[('standard_5', 'Standard Rated (5%)'), ('zero_0', 'Zero Rated (0%)'), ('exempt', 'Exempt'), ('reverse_charge', 'Reverse Charge')], max_length=20, null=True)),
                ('trn_expiry', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('use_same_shipping_address', models.BooleanField(default=True)),
                ('emirate', models.CharField(choices=[('abu_dhabi', 'Abu Dhabi'), ('dubai', 'Dubai'), ('sharjah', 'Sharjah'), ('ras_al_khaima', 'Ras Al Khaima'), ('ajman', 'Ajman'), ('fujairah', 'Fujairah'), ('umm_al_quwain', 'Umm Al Quwain'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(default='United Arab Emirates', max_length=50)),
                ('payment_terms', models.PositiveIntegerField(default=30, help_text='Payment terms in days', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('ytd_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_invoices', models.PositiveIntegerField(default=0)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.JSONField(blank=True, default=list, help_text='List of notes')),
                ('contacts', models.JSONField(blank=True, default=list, help_text='List of contact persons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='crm.customer')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='crm_custome_company_a7d034_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_name'], name='crm_custome_custome_4fbc25_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['industry'], name='crm_custome_industr_756824_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='crm_custome_created_1d27ae_idx'),
        ),
    ]
