# Generated by Django 5.0.2 on 2026-02-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customer_customercontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField()),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('AED', 'AED (UAE Dirham)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('GBP', 'GBP (British Pound)'), ('SAR', 'SAR (Saudi Riyal)'), ('INR', 'INR (Indian Rupee)')], default='AED', max_length=10)),
                ('payment_terms', models.PositiveIntegerField(default=30)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_overdue', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('online_payment', 'Online Payment')], max_length=20, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('payment_history', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='crm_invoice_invoice_6209f9_idx'), models.Index(fields=['customer_id'], name='crm_invoice_custome_1a34f8_idx'), models.Index(fields=['status'], name='crm_invoice_status_8cc065_idx'), models.Index(fields=['due_date'], name='crm_invoice_due_dat_5a7ece_idx'), models.Index(fields=['created_at'], name='crm_invoice_created_ec4cca_idx')],
            },
        ),
    ]
