# Generated by Django 5.0.2 on 2026-02-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='crm_invoice_custome_1a34f8_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id_backup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='crm_invoice_custome_1a34f8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_name'], name='crm_invoice_custome_a2d231_idx'),
        ),
    ]
