# Generated by Django 5.0.2 on 2026-02-10 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_customer',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_invoice',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_lead',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_status_2c1bc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_industr_dce405_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_source_0cf4cf_idx',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='custom_data',
            new_name='extra_data',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='value',
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='crm_lead_created_d9bbc3_idx'),
        ),
        migrations.DeleteModel(
            name='CustomerContact',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
