# Generated by Django 5.0.2 on 2026-02-12 13:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_applicable', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opening_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warehouse', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_code'], name='crm_invento_item_co_757982_idx'), models.Index(fields=['item_name'], name='crm_invento_item_na_796690_idx'), models.Index(fields=['category'], name='crm_invento_categor_c69803_idx'), models.Index(fields=['status'], name='crm_invento_status_c34e95_idx')],
            },
        ),
    ]
