# Generated by Django 5.0.2 on 2026-02-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
    model_name='expense',
    name='account',
    field=models.ForeignKey(
        on_delete=django.db.models.deletion.PROTECT,
        related_name='expenses',
        to='crm.account',
        null=True,          # 👈 ADD THIS
        blank=True
    ),
),

    ]
