# Generated by Django 5.0.2 on 2026-02-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='vendor_email',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='crm.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
    ]
