# Generated by Django 5.0.2 on 2026-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_expense_vendor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
