# Generated by Django 5.0.2 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_remove_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinvoice',
            name='is_posted_to_accounts',
            field=models.BooleanField(default=False),
        ),
    ]
