# Generated by Django 5.0.2 on 2026-02-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_expenseinvoice_is_posted_to_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseinvoice',
            name='is_posted_to_accounts',
        ),
    ]
