# Generated by Django 5.0.2 on 2026-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_remove_expenseinvoice_is_posted_to_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinvoice',
            name='invoice_type',
            field=models.CharField(default='EXPENSE', max_length=30),
        ),
    ]
