# Generated by Django 5.0.2 on 2026-02-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_inventoryinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryinvoice',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='inventoryinvoice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_invoices', to='crm.vendor'),
        ),
    ]
