# Generated by Django 5.0.2 on 2026-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_remove_inventoryinvoice_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
