# Generated by Django 5.0.2 on 2026-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='related_invoice_id',
            new_name='related_vendor_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='related_type',
            field=models.CharField(choices=[('none', 'None'), ('lead', 'Lead'), ('customer', 'Customer'), ('vendor', 'Vendor')], default='none', max_length=20),
        ),
    ]
