# Generated by Django 5.0.2 on 2026-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_bankaccount_bankreconciliationlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatementtransaction',
            old_name='matched_ledger_reference',
            new_name='matched_reference',
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankstatementtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankstatementtransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.bankaccount'),
        ),
        migrations.AlterField(
            model_name='bankstatementtransaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bankstatementtransaction',
            name='status',
            field=models.CharField(default='unmatched', max_length=20),
        ),
    ]
