# Generated by Django 5.0.2 on 2026-03-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_expenseattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
