# Generated by Django 5.0.2 on 2026-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_alter_expenseattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
